### PR TITLE
Webpack 5 requires dependencies to be absolute path

### PR DESCRIPTION
**Pull request by elsassph**
- ensure classpath and watch paths are absolute
- fix regression in hxml parsing (with test)

### CODE REVIEW

**Comment by clarkjones** [comment]
Getting a build error:
```
Module build failed (from ./node_modules/haxe-loader/index.js):
Haxe Loader: Compilation failed
```
This appears to be a problem introduced in an earlier update though.  I went ahead made the same changes in my local 0.10.0 release and it built fine.

yargs-parser seems to be the only version bump with a new major version so maybe that?

**Comment by clarkjones** [comment]
ok here's a follow up.
Reverting yargs-parser did work for me. 
After a little research I found there is an issue with parsing quotes in updated versions. My web pack build uses `--macro "include('...')" in the `extra` option
shell-parser seems to be a working alternative.

**Comment by elsassph** [comment]
@clarkjones indeed there was a subtle change in `yargs-parser` tokenization (for the better). It should be fixed now.

**Comment by clarkjones** [comment]
ok, works for me now.  thanks

**Pull request merged**
